config/routes.rb
Rails.application.routes.draw do
  resources :cloud_marcos
  resources :cloud_perfils
  get 'archivos/subir_archivos'

  get 'archivos/listar_archivos'

  get 'archivos/borrar_archivos'

  get 'archivos/guardar_comentarios'

  get 'test_sesiones/iniciar_sesion'

  get 'test_sesiones/cerrar_sesion'

  get 'test_sesiones/bienvenida'
  
  post "test_sesiones/iniciar_sesion"
  
  get "archivos/subir_archivos"
  post "archivos/subir_archivos"
  get "archivos/listar_archivos"
  post "archivos/borrar_archivos"
  get "archivos/ver"
  post "archivos/ver"
  	
  resources :cloud_tdps

root :to => 'test_sesiones#iniciar_sesion'

end

app/models/cloud_marco.rb
class CloudMarco < ActiveRecord::Base
end

app/controllers/cloud_marcos_controller.rb
class CloudMarcosController < ApplicationController
  before_action :set_cloud_marco, only: [:show, :edit, :update, :destroy]

  # GET /cloud_marcos
  # GET /cloud_marcos.json
  def index
    @cloud_marcos = CloudMarco.all
  end

  # GET /cloud_marcos/1
  # GET /cloud_marcos/1.json
  def show
  end

  # GET /cloud_marcos/new
  def new
    @cloud_marco = CloudMarco.new
  end

  # GET /cloud_marcos/1/edit
  def edit
  end

  # POST /cloud_marcos
  # POST /cloud_marcos.json
  def create
    @cloud_marco = CloudMarco.new(cloud_marco_params)

    respond_to do |format|
      if @cloud_marco.save
        format.html { redirect_to @cloud_marco, notice: 'Cloud marco was successfully created.' }
        format.json { render :show, status: :created, location: @cloud_marco }
      else
        format.html { render :new }
        format.json { render json: @cloud_marco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cloud_marcos/1
  # PATCH/PUT /cloud_marcos/1.json
  def update
    respond_to do |format|
      if @cloud_marco.update(cloud_marco_params)
        format.html { redirect_to @cloud_marco, notice: 'Cloud marco was successfully updated.' }
        format.json { render :show, status: :ok, location: @cloud_marco }
      else
        format.html { render :edit }
        format.json { render json: @cloud_marco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloud_marcos/1
  # DELETE /cloud_marcos/1.json
  def destroy
    @cloud_marco.destroy
    respond_to do |format|
      format.html { redirect_to cloud_marcos_url, notice: 'Cloud marco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cloud_marco
      @cloud_marco = CloudMarco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cloud_marco_params
      params.require(:cloud_marco).permit(:provedor, :descripcion, :tipo, :gasto_ingreso, :producto, :num_contrato, :catalogado, :saldo, :moneda, :vigencia)
    end
end

app/helpers/cloud_marcos_helper.rb
module CloudMarcosHelper
end

app/views/cloud_marcos/edit.html.erb
<%= render 'form' %>

app/views/cloud_marcos/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Data Tables</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="../../bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="dataTables.bootstrap.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="stilos.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="franja.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>T</b>dP</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Cloud</b>TdP</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>


 <!-- cerrar sesión -->

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
            <!-- Notifications: style can be found in dropdown.less -->
          
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            
              
             <%= link_to "Cerrar sesión", :controller => "test_sesiones", :action => "cerrar_sesion" %>
              
            </a>
            
          </li>
          <!-- Control Sidebar Toggle Button -->
          
        </ul>
      </div>
      
      
      
      
      
      
    </nav>
  </header>
  
  
  
  <!-- Left side column. contains the logo and sidebar -->
   <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
         
            <%= image_tag "s.png",:class => "img-circle",:alt => "User Image "%>	  
        </div>
        
        <div class="pull-left info">
          <p>squirtle</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <br>
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
      
        <div class="row">
  		<div class="col-md-8">		
   		</div>
  
</div>
        
   <!-- /. links de tablasssss -->
        
        <li class="treeview active">
          <a href="#">
            <i class="fa fa-table"></i> <span>Tablas disponibles</span>
            <i class="fa fa-angle-left pull-right"></i>
          </a>
          
          <ul class="treeview-menu">

            <li class="active"><a><i class="fa fa-circle-o"></i><%= link_to "T.Experiencias", :controller => "cloud_tdps" %></a></li>
            <li class="active"><a><i class="fa fa-circle-o"></i><%= link_to "T.Perfiles", :controller => "cloud_perfils" %></a></li>
            <li class="active"><a><i class="fa fa-circle-o"></i><%= link_to "T.Contratos", :controller => "cloud_marcos" %></a></li>
                       
          </ul>
          
        </li>
        
       
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
  
    <!-- finnnnn del asideeeee -->
  
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Tabla de datos
        <small>cloud cuu</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <!-- /.box -->

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">TdP cloud_cuu búsqueda</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
      
      
  <div class="table-responsive">        
 <table id="example1" class="table table-bordered table-striped">
              
   <thead>
    <tr>
      <th>Provedor</th>
      <th>Descripcion</th>
      <th>Tipo</th>
      <th>G_I</th>
      <th>Producto</th>
      <th>Num contrato</th>
      <th>Cata</th>
      <th>Saldo</th>
      <th>Mon</th>
      <th>Vigencia</th>
       <th>Opciones</th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    <% @cloud_marcos.each do |cloud_marco| %>
      <tr>
        <td><%= cloud_marco.provedor %></td>
        <td><%= cloud_marco.descripcion %></td>
        <td><%= cloud_marco.tipo %></td>
        <td><%= cloud_marco.gasto_ingreso %></td>
        <td><%= cloud_marco.producto %></td>
        <td><%= cloud_marco.num_contrato %></td>
        <td><%= cloud_marco.catalogado %></td>
        <td><%= cloud_marco.saldo %></td>
        <td><%= cloud_marco.moneda %></td>
        <td><%= cloud_marco.vigencia %></td>
        <td button type="button" class="btn btn-default"><%= link_to 'Subir', cloud_marco %></td>
        <td button type="button" class="btn btn-default"><%= link_to 'Editar', edit_cloud_marco_path(cloud_marco) %></td>
        <td button type="button" class="btn btn-default"><%= link_to 'Clear', cloud_marco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div button type="button" class="btn btn-default"><%= link_to 'New Cloud marco', new_cloud_marco_path %></div>
	<div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 0.0.1
    </div>
    <strong>Dev: emanuel.mendoza@telefonica.com </strong>
 
  </footer>

  <!-- Control Sidebar -->
  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.0 -->

<!-- Bootstrap 3.3.6 -->

<!-- DataTables -->
<script src="jjquery.dataTables.min.js"></script>

<script src="dataTables.bootstrap.min.js"></script>
<!-- SlimScroll -->

<!-- FastClick -->

<!-- AdminLTE App -->
<script src="aapp.min.js"></script>
<!-- AdminLTE for demo purposes -->
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });
  });
</script>
</body>
</html>

app/views/cloud_marcos/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', cloud_marcos_path %>

app/views/cloud_marcos/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Cloud</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="../../bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="dataTables.bootstrap.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="stilos.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="franja.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>T</b>dP</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Cloud</b>TdP</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>



      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
            <!-- Notifications: style can be found in dropdown.less -->
          
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            
              
             <%= link_to "Cerrar sesión", :controller => "test_sesiones", :action => "cerrar_sesion" %>
              
            </a>
            
          </li>
          <!-- Control Sidebar Toggle Button -->
          
        </ul>
      </div>
      
      
    </nav>
    
  </header>
  
  
  
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
         
            <%= image_tag "s.png",:class => "img-circle",:alt => "User Image "%>	  
        </div>
        
        <div class="pull-left info">
          <p>squirtle</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <br>
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        
      
        <div class="row">
  		<div class="col-md-8">		
   		</div>
  
</div>
        
   <!-- /. links de tablasssss -->
        
        <li class="treeview active">
          <a href="#">
            <i class="fa fa-table"></i> <span>Tablas disponibles</span>
            <i class="fa fa-angle-left pull-right"></i>
          </a>
          
          <ul class="treeview-menu">
      		
      		 
            <li class="active"><a><i class="fa fa-circle-o"></i><%= link_to "T.Experiencias", :controller => "cloud_tdps" %></a></li>
            <li class="active"><a><i class="fa fa-circle-o"></i><%= link_to "T.Perfiles", :controller => "cloud_perfils" %></a></li>
            <li class="active"><a><i class="fa fa-circle-o"></i><%= link_to "T.Contratos", :controller => "cloud_marcos" %></a></li>
           		
      		   
            
          </ul>
          
        </li>
        
       
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Tabla de datos
        <small>cloud cuu</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <!-- /.box -->

<!-- /.box inicia la parte del cuerpo de al pagina webbbbbbbbbb-->
          
          <div class="box">
            <div class="box-header">

             
        <p id="notice"><%= notice %></p>
        <br>

<div class="row">
  		<div class="col-md-6">
<p id="notice"><%= notice %></p>

<p>
  <strong>Provedor:</strong>
  <%= @cloud_marco.provedor %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @cloud_marco.descripcion %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @cloud_marco.tipo %>
</p>

<p>
  <strong>Gasto ingreso:</strong>
  <%= @cloud_marco.gasto_ingreso %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @cloud_marco.producto %>
</p>

<p>
  <strong>Num contrato:</strong>
  <%= @cloud_marco.num_contrato %>
</p>

<p>
  <strong>Catalogado:</strong>
  <%= @cloud_marco.catalogado %>
</p>

<p>
  <strong>Saldo:</strong>
  <%= @cloud_marco.saldo %>
</p>

<p>
  <strong>Moneda:</strong>
  <%= @cloud_marco.moneda %>
</p>

<p>
  <strong>Vigencia:</strong>
  <%= @cloud_marco.vigencia %>
</p>


<br/>

<% if !Dir.exists?("public/contrato/" + @cloud_marco.num_contrato) %>
   
   <%= Dir.mkdir "public/contrato/" + @cloud_marco.num_contrato %> 
<% end %>

 <strong> Subir contrato marco :</strong>
<h4>-----------------------------------------------------------------</h4>
<p>
  
  <%= form_tag({:controller => "archivos", :action => "subir_archivos"}, :method => "post", :multipart => true) do %>
   <%= file_field_tag "archivo", :required => "required" %>
  
   <%= label_tag "dire", "dire" %>
   <br />
   <%= text_field_tag "dire","public/contrato/"+ @cloud_marco.num_contrato,:required => "required" %>
   <br />
   
   <%= submit_tag "Subir archivo" %>
<% end %>


<% if @formato_erroneo %>
  <div>
     <p> El formato ingresado es incorrecto. Usted sólo puede subir archivos .pdf, .doc y .docx </p>

  </div>
<% end %>

<%= link_to 'Edit', edit_cloud_marco_path(@cloud_marco) %> |
<%= link_to 'Back', cloud_marcos_path %>
	
<br>
			
  		</div>
  
  	<div class="col-md-6">
  


   
   <h3>Archivos subidos</h3>
  	<% @d="public/contrato/" + @cloud_marco.num_contrato ;%>
	<% @archivos = Dir.entries(@d); %>
<ul>
   <% @archivos.each do |a| %>
   <% if a == "." or a == ".." then next end; %>
   <li>
   	<% @p= @cloud_marco.num_contrato + "/" ;%>
      <strong> <%= a %> </strong>
      <br>  
      <a target="_blank" href="/contrato/<%= @p + a %>">Ver o Descargar </a> | 
      
      
     
   </li>
<% end %>

 
	</div>
<div>	


  <div class="box-body">
      
      
  </div>
          
            </div>
            <!-- /.box-header -->
          
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 0.0.1
    </div>
    <strong>Dev: emanuel.mendoza@telefonica.com </strong>
 
  </footer>

  <!-- Control Sidebar -->
  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.0 -->

<!-- Bootstrap 3.3.6 -->

<!-- DataTables -->
<script src="jjquery.dataTables.min.js"></script>

<script src="dataTables.bootstrap.min.js"></script>
<!-- SlimScroll -->

<!-- FastClick -->

<!-- AdminLTE App -->
<script src="aapp.min.js"></script>
<!-- AdminLTE for demo purposes -->
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });
  });
</script>
</body>
</html>